clout_mafia/urls.py
from django.contrib import admin
from django.urls import path, include
# To allow django to see the media files
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # Include all of the login, log out, password reset etc. from allauth
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('basket/', include('basket.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('testimonials/', include('testimonials.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # Set of empty path to indicate this is the route URL,
    # and its going to render views.index with the name Home.

    path('', views.index, name='home'),
    path('refunds/', views.refunds, name='refunds'),
    path('privacy/', views.privacy, name='privacy'),
    path('terms/', views.terms, name='terms'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('send/', views.send_email, name='send_email'),
]

testimonials/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # Set of empty path to indicate this is the route URL,
    # and its going to render views.index with the name Home.

    path('', views.all_testimonials, name='testimonials'),
    path('add/', views.add_testimonial, name='add_testimonial'),
    path('edit/<int:testimonial_id>/',
        views.edit_testimonial, name='edit_testimonial'),
    path('delete/<int:testimonial_id>/',
        views.delete_testimonial, name='delete_testimonial'),
]

testimonials/models.py
from django.db import models
from django.contrib.auth.models import User


class Testimonial(models.Model):
    """
    Testimonal modal which would display the fields required
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    date = models.DateField(auto_now_add=True)
    time = models.TimeField(auto_now_add=True)
    title = models.CharField(max_length=254)
    message = models.TextField()
    rating = models.DecimalField(
        max_digits=1, decimal_places=0)

    # String to return the review titles
    def __str__(self):
        return self.title

testimonials/forms.py
from django import forms
from .models import Testimonial


class TestimonialForm(forms.ModelForm):

    class Meta:
        # To define the model and it will include ALL the fields.
        model = Testimonial
        fields = ('title', 'message', 'rating')

    # To override the init method
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        placeholders = {
            'title': 'Testimonial Title',
            'message': 'Type testimonial message here',
            'rating': 'Rating 1 - 5',
        }

        # Only displaying the placeholder fields
        for field in self.fields:
            placeholder = placeholders[field]
            self.fields[field].widget.attrs['placeholder'] = placeholder
            self.fields[field].widget.attrs['class'] = 'border-black rounded-0'
            self.fields[field].label = False

testimonials/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.contrib import messages
from .models import Testimonial
from django.contrib.auth.decorators import login_required
from django.db.models.functions import Lower
from .forms import TestimonialForm


def all_testimonials(request):
    """
    A view to return all the testimonials made by users
    """

    testimonials = Testimonial.objects.all().order_by('-date', '-time')
    sort = None
    direction = None

    # Checking if request.GET exists
    if request.GET:
        if 'sort' in request.GET:
            # Allowing sort to equals sortkey
            sortkey = request.GET['sort']
            sort = sortkey
            if sortkey == 'title':
                sortkey = 'lower_title'
                # Annotate the list of products with the new field
                testimonials = testimonials.annotate(lower_title=Lower('title'))

            if 'direction' in request.GET:
                direction = request.GET['direction']
                # Check if the direction is descending or ascending
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            # To sort the testimonials
            testimonials = testimonials.order_by(sortkey)

    sorting_testimonials = f'{sort}_{direction}'

    user = request.user
    admin = request.user.is_superuser

    context = {
        'testimonials': testimonials,
        'sorting_testimonials': sorting_testimonials,
        'user': user,
        'admin': admin,
    }

    return render(request, 'testimonials/testimonials.html', context)


@login_required
def add_testimonial(request):
    """
    Add a testimonial to the app
    """

    # Checking if the request method is post
    if request.method == 'POST':
        form = TestimonialForm(request.POST)
        # checking if the form is a valid
        if form.is_valid():
            data = form.save(commit=False)
            data.user = request.user
            data.save()

            messages.success(request, 'Thank you for taking \
                your time to write a review \
            Your testimonial has been add!')
            # On success, redirect the user to the testimonials home page
            return redirect(reverse('testimonials'))
        else:
            messages.error(request, 'Failed to add testimonial. Please \
                ensure the form is valid.')
    else:
        form = TestimonialForm()

    template = 'testimonials/add_testimonial.html'
    context = {
        'form': form,
    }

    return render(request, template, context)


@login_required
def edit_testimonial(request, testimonial_id):
    """
    Edit a product in the store
    """
    # Storing both logged in users and superusers to vars
    user = request.user
    admin = request.user.is_superuser

    # Prefilling the form using the product_object_or_404
    testimonial = get_object_or_404(Testimonial, pk=testimonial_id)
    # if to check if logged in user is same as the testimonial user
    # or is the admin user, so they can edit testimonial.
    if user == testimonial.user or admin:
        if request.method == 'POST':
            # Checking if the request method is post, telling the instance to
            # post new information of that instance of the testimonial.
            form = TestimonialForm(request.POST, instance=testimonial)
            if form.is_valid():
                form.save()
                messages.success(request, 'Successfully updated the testimonial!')
                return redirect(reverse('testimonials'))
            else:
                messages.error(request, 'Failed to update the testimonial. \
                    Please ensure the form is valid.')
        else:
            # Creating the instance of the testimonial form
            form = TestimonialForm(instance=testimonial)
            messages.info(request, f'You are editting the testimonial \
                for "{testimonial.title}"!')

        # Informing it which template to use.
        template = 'testimonials/edit_testimonial.html'
        context = {
            'form': form,
            'testimonial': testimonial,
        }

        return render(request, template, context)
    else:
        messages.error(request, 'Access Denied! You do not own this testimonial')
        return redirect(reverse('testimonials'))


@login_required
def delete_testimonial(request, testimonial_id):
    """
    Delete a testimonial from the app
    """
    # Storing both logged in users and superusers to vars
    user = request.user
    admin = request.user.is_superuser

    # Prefilling the form using the product_object_or_404
    testimonial = get_object_or_404(Testimonial, pk=testimonial_id)
    # if to check if logged in user is same as the testimonial user
    # or is the admin user, so they can edit testimonial.
    if user == testimonial.user or admin:
        testimonial.delete()
        messages.success(request, 'The testimonial has been deleted!')
        return redirect(reverse('testimonials'))
    else:
        messages.error(request, 'Access Denied! You do own this testimonial')
        return redirect(reverse('testimonials'))

testimonials/templates/testimonials/add_testimonial.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col">

        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="overlay"></div>
<div class="container">
    <!-- Title of the page -->
    <div class="row offset-md-2 col-md-8">
        <div class="col-12 text-center mt-lg-2 mt-md-2">
            <h2 class="title mt-lg-4 mt-md-2 mt-3">Add Testimonial</h2>
            <hr class="w-50 mb-3 mb-md-5 mx-auto">
            <h4 class="mb-4">Please leave a testimonial from the experience that you have had. 
            </h4>

        </div>
    </div>

    <div class="row offset-md-2 col-md-8">
        <div class="col-12">
            <!-- To render the form that will be filled out to add a testimonial -->
            <form method="POST" action="{% url 'add_testimonial' %}" class="form mb-2">
                {% csrf_token %}
                {{ form.title|as_crispy_field }}
                {{ form.message|as_crispy_field }}
                {{ form.rating|as_crispy_field }}
                <!-- Buttons to go back to the products page and to add a product -->
                <div class="text-center">
                    <a class="btn btn-outline-black rounded-0 col-12 col-md-5 mb-3" href="{% url 'testimonials' %}">Back To Testimonials</a>
                    <button class="btn btn-grey rounded-0 col-12 col-md-5 mb-3" type="submit">Add Testimonial</button>
                </div>
            </form>
        </div>
    </div>

</div>
{% endblock %}

{% block afterloadjs %}
{{ block.super }}
<script type="text/javascript">
    $(document).ready(function () {
        $("#id_rating").attr({"max" : 5, "min" : 1});
    });
</script>
{% endblock %}

testimonials/templates/testimonials/edit_testimonial.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col">

        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="overlay"></div>
<div class="container">
    <!-- Title of the page -->
    <div class="row offset-md-2 col-md-8">
        <div class="col-12 text-center mt-lg-2 mt-md-2">
            <h2 class="title mt-lg-4 mt-md-2 mt-3">Edit Testimonial</h2>
            <hr class="w-50 mb-3 mb-md-5 mx-auto">
        </div>
    </div>

    <div class="row offset-md-2 col-md-8">
        <div class="col-12">
            <!-- To render the form that will be filled out to add a testimonial -->
            <form method="POST" action="{% url 'edit_testimonial' testimonial.id %}" class="form mb-2">
                {% csrf_token %}
                {{ form | crispy }}
                <!-- Buttons to go back to the products page and to add a testimonial -->
                <div class="text-center">
                    <a class="btn btn-outline-black rounded-0 col-12 col-md-4 mb-3" href="{% url 'testimonials' %}">Cancel</a>
                    <button class="btn btn-grey rounded-0 col-12 col-lg-4 col-md-5 mb-3" type="submit">Update Testimonial</button>
                </div>
            </form>
        </div>
    </div>

</div>
{% endblock %}

{% block postloadjs %}
{{ block.super }}
<script type="text/javascript">
    $(document).ready(function () {
        $("#id_rating").attr({"max" : 5, "min" : 1});
    });
</script>
{% endblock %}

testimonials/templates/testimonials/testimonials.html
{% extends "base.html" %}
{% load static %}

{% block other_css %}
<link rel="stylesheet" href="{% static 'checkout/css/checkout.css' %}">
{% endblock %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col">

        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="overlay"></div>
<div class="container mb-2">
    <!-- Title of the page-->
    <div class="row g-0">
        <div class="col-12 text-center mt-lg-2 mt-md-2">
            <h2 class="title mt-lg-4 mt-md-2 mt-3">Testimonials</h2>
            <hr class="w-50 mb-3 mb-md-5 mx-auto">
        </div>

        <div class="row g-0">
            <div class="col-12 mx-auto">
                <!-- Write a testimonial button -->
                <div class="col-12 text-center my-3">
                    <a class="btn btn-grey rounded-2" href="{% url 'add_testimonial' %}">Write a Testimonial</a>
                </div>
            </div>
            <div class="row g-0">
                <div class="sort-select-wrapper my-auto d-flex justify-content-lg-end justify-content-center">
                    <!-- Setting the sort selector for the user to be able to choose the order they would like to see -->
                    <select id="sort-selector"
                        class="custom-select custom-select-sm rounded-2 border border-{% if sorting_testimonials != 'None_None' %}info{% else %}black{% endif %} w-25 w-auto">
                        <option value="reset" {% if sorting_testimonials == 'None_None' %}selected{% endif %}>Sort by...
                        </option>
                        <option value="rating_asc" 
                        {% if sorting_testimonials == 'rating_asc' %}selected{% endif %}>Rating (low to high)</option>
                        <option value="rating_desc" 
                        {% if sorting_testimonials == 'rating_desc' %}selected{% endif %}>Rating (high to low)</option>
                        <option value="date_asc" 
                        {% if sorting_testimonials == 'date_asc' %}selected{% endif %}>Date (New to Old)</option>
                        <option value="date_desc" 
                        {% if sorting_testimonials == 'date_desc' %}selected{% endif %}>Date (Old to New)</option>
                        <option value="title_asc" 
                        {% if sorting_testimonials == 'title_asc' %}selected{% endif %}>Title (A-Z)</option>
                        <option value="title_desc"
                        {% if sorting_testimonials == 'title_desc' %}selected{% endif %}>Title (Z-A)</option>
                    </select>
                </div>
            </div>
                <div class="row g-0">
                    <div class="product-container col-12 col-md-12 order-md">
                    <!-- Loop to go through the testimonials in a side ways card view -->
                    {% for testimonial in testimonials %}
                        <div class="card mt-3">
                            <div class="row g-0">
                                <div class="card-header text-center border col-md-4">
                                    <div class="row">
                                        <div class="col-12">
                                            {{ testimonial.user }}
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-12">
                                            <!-- Stars from font awesome which would be associated with the rating user provided -->
                                            {% if testimonial.rating == 5 %}
                                                <i class="fas fa-star mr-1"></i>
                                                <i class="fas fa-star mr-1"></i>
                                                <i class="fas fa-star mr-1"></i>
                                                <i class="fas fa-star mr-1"></i>
                                                <i class="fas fa-star mr-1"></i> {{ testimonial.rating }} / 5
                                            {% elif testimonial.rating == 4 %}
                                                <i class="fas fa-star mr-1"></i>
                                                <i class="fas fa-star mr-1"></i>
                                                <i class="fas fa-star mr-1"></i>
                                                <i class="fas fa-star mr-1"></i> {{ testimonial.rating }} / 5
                                            {% elif testimonial.rating == 3 %}
                                                <i class="fas fa-star mr-1"></i>
                                                <i class="fas fa-star mr-1"></i>
                                                <i class="fas fa-star mr-1"></i> {{ testimonial.rating }} / 5
                                            {% elif testimonial.rating == 2 %}
                                                <i class="fas fa-star mr-1"></i>
                                                <i class="fas fa-star mr-1"></i> {{ testimonial.rating }} / 5
                                            {% elif testimonial.rating == 1 %}
                                                <i class="fas fa-star mr-1"></i> {{ testimonial.rating }} / 5
                                            {% else %}
                                                <small class="text-muted">No Rating</small>
                                            {% endif %}
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-12">
                                            <p class="card-text"><small class="text-muted">
                                                Posted on: {{ testimonial.date }}
                                            </small></p>
                                        </div>
                                    </div>
                                    <!-- The user has the power to edit/delete their own testimonials -->
                                    {% if user == testimonial.user or admin %}
                                    <div class="row">
                                        <div class="col-12">
                                            <p class="card-text">
                                                <small class="text-muted">
                                                    <a href="{% url 'edit_testimonial' testimonial.id %}" class="btn btn-primary btn-edit btn-sm" role="button"><span>Edit</span></a> |
                                                    <a href="{% url 'delete_testimonial' testimonial.id %}" class="btn btn-danger btn-delete btn-sm" role="button"><span>Delete</span></a> 
                                                </small>
                                            </p>
                                        </div>
                                    </div>
                                    {% endif %}
                                        
                                    </div>
                                    <div class="col-md-8">
                                        <div class="card-body">
                                            <h5 class="card-title test-title">{{ testimonial.title }}</h5>
                                            <p class="card-text text-muted test-message">"{{ testimonial.message }}"</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}        
                        </div>
                        <div class="row">
                            <div class="col-6 offset-md-5 offset-4 my-3">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>                            
{% endblock %}

{% block afterloadjs %}
{{ block.super }}
    <script type="text/javascript">
        /* once capturing the change event from the source selector
    two variables set, one for the selector and the other for a new url for the object 
    which takes the window location */
        $('#sort-selector').change(function () {
            var selector = $(this);
            var currentUrl = new URL(window.location);

            /* get the value from the selector box and the breaking them out 
            into sort and direction*/
            var selectedVal = selector.val();
            if (selectedVal != "reset") {
                var sort = selectedVal.split("_")[0];
                var direction = selectedVal.split("_")[1];

                /* change the get parameters to the method calls */
                currentUrl.searchParams.set("sort", sort);
                currentUrl.searchParams.set("direction", direction);

                /* change the current location to the updated URL  */
                window.location.replace(currentUrl);
            } else {
                currentUrl.searchParams.delete("sort");
                currentUrl.searchParams.delete("direction");

                window.location.replace(currentUrl);
            }
        })
    </script>
{% endblock %}