basket/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # This is the route URL or the page we are creating

    path('', views.view_basket, name='view_basket'),
    path('add/<item_id>/', views.add_to_basket, name='add_to_basket'),
    path('remove/<item_id>/',
         views.remove_from_basket, name='remove_from_basket'),
]

clout_mafia/urls.py
from django.contrib import admin
from django.urls import path, include
# To allow django to see the media files
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # Include all of the login, log out, password reset etc. from allauth
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('basket/', include('basket.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('testimonials/', include('testimonials.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # Set of empty path to indicate this is the route URL,
    # and its going to render views.index with the name Home.

    path('', views.index, name='home'),
    path('refunds/', views.refunds, name='refunds'),
    path('privacy/', views.privacy, name='privacy'),
    path('terms/', views.terms, name='terms'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('send/', views.send_email, name='send_email'),
]

checkout/models.py
import uuid

from django.db import models
from django.db.models import Sum
from django.conf import settings

from django_countries.fields import CountryField

from products.models import Product
from profiles.models import UserProfile

# Will handle all orders across the store


class Order(models.Model):
    # Editable field means the field can not be changed was created
    order_number = models.CharField(max_length=32, null=False, editable=False)
    user_profile = models.ForeignKey(
        UserProfile, on_delete=models.SET_NULL, null=True, blank=True, related_name='orders')
    full_name = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    address_line1 = models.CharField(max_length=80, null=False, blank=False)
    address_line2 = models.CharField(max_length=80, null=True, blank=True)
    town_or_city = models.CharField(max_length=40, null=False, blank=False)
    county_state = models.CharField(max_length=80, null=True, blank=True)
    postcode = models.CharField(max_length=20, null=True, blank=True)
    country = CountryField(
        blank_label='Country *', null=False, blank=False)
    # Auto_now will be automatically generated as soon as the
    # user presses the buy now button
    purchase_date = models.DateTimeField(auto_now_add=True)
    delivery_cost = models.DecimalField(
        max_digits=6, decimal_places=2, null=False, default=0)
    order_total = models.DecimalField(
        max_digits=10, decimal_places=2, null=False, default=0)
    grand_price = models.DecimalField(
        max_digits=10, decimal_places=2, null=False, default=0)
    original_basket = models.TextField(null=False, blank=False, default='')
    stripe_pid = models.CharField(
        max_length=254, null=False, blank=False, default='')

    def _generate_order_number(self):
        """"
        The underscore is to define that it is a private method
        which would only be used inside this class but this class is to create
        a random and unique order number using the UUID
        """
        return uuid.uuid4().hex.upper()

        print(self.order_number)

    def update_final_total(self):
        """
        Update the final total each time a line item has been added
        and the delivery costs
        """
        # Setting the order total to lineitem_total_sum, by adding
        # 0 at the end, it will prevent an error if we manually delete all the
        # line items for an order by making sure that this sets the
        # order total to 0
        self.order_total = self.lineitems.aggregate(Sum('lineitem_total'))['lineitem_total__sum'] or 0
        # Using what has been set in settings for delivery cost and
        # standard delivery percentage
        if self.order_total < settings.FREE_DELIVERY_LIMIT:
            self.delivery_cost = self.order_total * settings.STANDARD_DELIVERY_PERCENTAGE / 100
        else:
            self.delivery_cost = 0
        self.grand_price = self.order_total + self.delivery_cost
        self.save()

    def save(self, *args, **kwargs):
        """
        Will override the original save method to set the order number,
        If it has not already been set.
        """
        # If the order does not have an order number, it will
        # create one and then save
        if not self.order_number:
            self.order_number = self._generate_order_number()
        super().save(*args, **kwargs)

    # String method to return the order number
    def __str__(self):
        return self.order_number

    """
    Order Line Product class is set up so when an order instance is created,
    it will go through the list of line items, amend the calculations if
    need to be, and then attach it to the order.
    """


class OrderLineItem(models.Model):
    # The related name is so we can the call easier to make,
    # for example order.lineitems.filter
    order = models.ForeignKey(
        Order, null=False, blank=False, on_delete=models.CASCADE, related_name='lineitems')
    product = models.ForeignKey(
        Product, null=False, blank=False, on_delete=models.CASCADE)
    product_size = models.CharField(max_length=2, null=True, blank=True)
    product_sold = models.CharField(max_length=2, null=True, blank=True)
    quantity = models.IntegerField(null=False, blank=False, default=0)
    lineitem_total = models.DecimalField(
        max_digits=6, decimal_places=2, null=False, blank=False, editable=False)

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the line item total
        update the order total
        """
        self.lineitem_total = self.product.price * self.quantity
        super().save(*args, **kwargs)

    # String method to return the sku of each product along with the
    # order number for which it is related to
    def __str__(self):
        return f'SKU {self.product.sku} on order {self.order.order_number}'

basket/views.py
from django.shortcuts import get_object_or_404, render, redirect, HttpResponse
from django.contrib import messages

from products.models import Product

# Create your views here.


def view_basket(request):
    """
    A view that loads the basket contents page
    """

    return render(request, 'basket/basket.html')


# Function to take both the request and add the product id to the basket
def add_to_basket(request, item_id):
    """
    Add a quantity of the specified product to the shopping basket
    """

    # Get the quantity from the basket and url to redirect
    # the user to previous page
    product = get_object_or_404(Product, pk=item_id)
    size = None
    if 'product_size' in request.POST:
        size = request.POST['product_size']
    quantity = int(request.POST.get('quantity'))
    redirect_url = request.POST.get('redirect_url')
    # Session created till the browser is closed to keep the user
    # shopping or if they would like to come back to it
    basket = request.session.get('basket', {})

    # If statement to check if a product with sizes is added or not.
    if size:
        # If the product is in basket
        if item_id in list(basket.keys()):
            # Condition: has the same size, increase quantity
            if size in basket[item_id]['items_by_size'].keys():
                basket[item_id]['items_by_size'][size] = quantity
                messages.error(request, f'"{product.name}" is already \
                    in the basket')
            else:
                # Same item, different size, add it as a new item.
                basket[item_id]['items_by_size'][size] = quantity
        else:
            basket[item_id] = {'items_by_size': {size: quantity}}
    else:
        # Adding the product and quantity in the basket, and if the product
        # is already there, add the quantity to the basket
        if item_id in list(basket.keys()):
            messages.error(
                request, f'"{product.name}" is already in the basket')
        else:
            basket[item_id] = quantity
            messages.success(request, f'"{product.name}" has been added to \
                the basket.')

    # Overwriting the variable in the session with the updated
    # version of the basket
    request.session['basket'] = basket
    print(request.session['basket'])
    return redirect(redirect_url)


# Function to remove the product from the basket
def remove_from_basket(request, item_id):
    """
    Remove the item from the shopping basket
    """

    # Try block to catch any expections that might
    # happen with a server 500 error
    try:
        product = get_object_or_404(Product, pk=item_id)
        basket = request.session.get('basket', {})
        basket.pop(item_id)

        request.session['basket'] = basket
        messages.success(request, f'"{product.name}" has been \
            removed from the basket.')
        return HttpResponse(status=200)

    except Exception as e:
        messages.error(request, f'Error removing item "{e}"')
        return HttpResponse(status=500)

basket/templates/basket/basket-total.html
<!-- To display the financial break down summary of the Total, the delivery price and the grand total  -->
<div class="price-small bg-light border border-2 rounded-3 p-3 mb-2">
    <h6 class="price-small"><strong>Basket Total: £{{ total|floatformat:2 }}</strong></h6>
    <h6 class="price-small">Delivery: £{{ delivery|floatformat:2 }}</h6>
    <h4 class="price-small mt-4"><strong>Grand Total: £{{ grand_price|floatformat:2 }}</strong></h4>
    {% if free_delivery_message > 0 %}
    <p class="price-small offset-sm-2 col-12 col-md-10 mb-1 text-danger fs-6">
        Spend <strong>£ {{ free_delivery_message }}</strong> more to get free delivery!
    </p>
    {% endif %}
    <tr>
        <!-- To take the user back to the all products page or to take them to the checkout page -->
        <td colspan="12" class="text-end">
            {% include "basket/checkout-buttons.html" %}
        </td>
    </tr>
</div>

basket/templates/basket/basket.html
{% extends "base.html" %}
{% load static %}
{% load basket_tools %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col">

        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container mb-2">
    <!-- Title of the page-->
    <div class="row">
        <div class="col text-center mt-lg-2 mt-md-2">
            <h2 class="title title-space mt-lg-4 mt-md-2">Shopping Basket</h2>
            <hr class="w-50 mb-3 mb-md-5 mx-auto">
        </div>
        <div class="row mx-auto">
            <!-- If something is in the basket, the table of contents will display it here -->
            {% if basket_products %}
            <!-- Only will be displayed for small screen devices -->
            <div class="d-block d-md-none">
                <div class="row text-center">
                    <div class="col">
                        {% include "basket/basket-total.html" %}
                    </div>
                </div>
                <!-- Will create a new row for each product that is added to the basket -->
                {% for item in basket_products %}
                <div class="row text-center">
                    <div class="col-12 col-sm-6 mb-2">
                        <!-- Including the product image -->
                        {% include "basket/product-image.html" %}
                    </div>
                    <div class="col-12 col-sm-6 mb-2">
                        <!-- Including the details of the product -->
                        {% include "basket/product-info.html" %}
                    </div>
                    <div class="col-12 col-sm-6 mb-2">
                        <!-- Including the size of the product (shoe) -->
                        {% include "basket/product-size.html" %}
                    </div>
                    <!-- Price and remove button placeholder -->
                    <div class="col-12 col-sm-6 order-sm-last">
                        <p class="my-0">£ {{ item.product.price | calc_subtotal:item.quantity }}</p>
                        <a class="btn btn-danger btn-sm remove-item float-right"
                            id="remove_{{ item.item_id }}"><small>Remove</small></a>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <!-- line to separate each item -->
                        <hr>
                    </div>
                </div>
                {% endfor %}
            </div>
            <div class="col-8 col-lg-8 ">
                <!-- Table headers for the basket -->
                <div class="table-responsive rounded d-none d-md-block">
                    <table class="table table-sm table-borderless">
                        <thead class="text-black">
                            <tr>
                                <th scope="col">Product Info</th>
                                <th scope="col"></th>
                                <th scope="col"></th>
                                <th scope="col">Subtotal</th>
                            </tr>
                        </thead>
                        <!-- For each item in the basket, it will create a new row for it -->
                        {% for item in basket_products %}
                        <tr>
                            <td class="p-3 w-25">
                                {% include "basket/product-image.html" %}
                            </td>
                            <td class="py-3">
                                {% include "basket/product-info.html" %}
                            </td>
                            <td class="py-3 w-25">
                                {% include "basket/product-size.html" %}
                            </td>
                            <td class="py-3 checkout_price">
                                <p class="my-0">£ {{ item.product.price }}</p>
                                <a class="btn btn-danger btn-sm remove-item float-right"
                                    id="remove_{{ item.item_id }}"><small>Remove</small></a>
                                    <!-- This is for the quantity field so they can increase o rdecrease when when they want
                                    as well update the bag once the quantity has been confirmed by the user, i have hidden 
                                    this field as it is not required in my project but required for posting towards the end -->
                                    <td class="py-3 w-25 d-none">
                                        <form class="form update-form" method="POST" action="">
                                            {% csrf_token %}
                                            <div class="form-group">
                                                <div class="input-group">
                                                    <div class="input-group-prepend">
                                                        <button class="decrement-qty btn btn-sm btn-grey rounded-0" 
                                                            data-item_id="{{ item.item_id }}" id="decrement-qty_{{ item.item_id }}">
                                                            <span>
                                                                <i class="fas fa-minus fa-sm"></i>
                                                            </span>
                                                        </button>
                                                    </div>
                                                    <input class="form-control form-control-sm qty_input" type="number"
                                                        name="quantity" value="{{ item.quantity }}" min="1" max="99"
                                                        data-item_id="{{ item.item_id }}"
                                                        id="id_qty_{{ item.item_id }}">
                                                    <div class="input-group-append">
                                                        <button class="increment-qty btn btn-sm btn-grey rounded-0"
                                                            data-item_id="{{ item.item_id }}" id="increment-qty_{{ item.item_id }}">
                                                            <span>
                                                                <i class="fas fa-plus fa-sm"></i>
                                                            </span>
                                                        </button>
                                                    </div>
                                                    {% if item.product.has_sizes %}
                                                        <input type="hidden" name="product_size" value="{{ item.size }}">
                                                    {% endif %}
                                                </div>
                                            </div>
                                        </form>
                                        <a class="update-link text-info"><small>Update</small></a>
                                        <a class="remove-item text-danger float-right" id="remove_{{ item.item_id }}" data-product_size="{{ item.size }}"><small>Remove</small></a>
                                    </td>
                            </td>
                        </tr>
                        {% endfor %}
                    </table>
                </div>
                {% else %}
                <!-- Message if the bag is empty and a link to go back to all products with a 
                    message and a button to go back shopping-->
                <p class="lead mt-5">No items have been added to the Basket.</p>
                <a href="{% url 'products' %}" class="btn btn-outline-black rounded-0 btn-lg my-5">
                    <span class="icon">
                        <i class="fas fa-chevron-left"></i>
                    </span>
                    <span class="text-uppercase">Carry on Shopping</span>
                </a>
                {% endif %}
            </div>
            <!-- Basket total and buttons side button -->
            {% if basket_products %}
            <div
                class="basket-summary offset-lg-7 col-lg-3 col-6 offset-md-7 col-md-4 justify-content-end position-fixed text-end d-none d-md-block">
                {% include "basket/basket-total.html" %}
            </div>
            {% endif %}
        </div>
    </div>

    {% endblock %}

    {% block afterloadjs %}
    {{ block.super }}
    <script type="text/javascript">
        // Remove the token and item from the dictionary and reload on click
        $('.remove-item').click(function(e) {
            var csrfToken = "{{ csrf_token }}";
            var itemId = $(this).attr('id').split('remove_')[1];
            var size = $(this).data('product_size');
            var url = `/basket/remove/${itemId}/`;
            var data = {'csrfmiddlewaretoken': csrfToken, 'product_size': size};

            $.post(url, data)
            .done(function() {
                location.reload();
            });
        })
    </script>

    {% endblock %}

basket/templates/basket/checkout-buttons.html
<!-- Buttons for the basket page -->
<div class="row justify-content-end">
    <!-- To go back to the products page -->
    <a href="{% url 'products' %}"
        class="btn btn-outline-black rounded-2 btn-lg col-12 col-md-10 col-lg-12 col-md-12 mt-3 p-1">
        <span class="icon">
            <i class="fas fa-chevron-left"></i>
        </span>
        <span class="text-uppercase fs-6">Carry on Shopping</span>
    </a>
</div>
<div class="row justify-content-end">
    <br>
    <!-- To proceed to checkout -->
    <a href="{% url 'checkout' %}"
        class="btn btn-grey rounded-2 btn-lg col-12 col-md-10 col-lg-12 col-md-12 mt-2 mt-md-2 p-1">
        <span class="text-uppercase fs-6">Secure Checkout</span>
        <span class="icon">
            <i class="fas fa-lock"></i>
        </span>
    </a>
</div>

basket/templates/basket/product-colour.html
<!-- To display the the colour of the product in the basket -->
<p class="my-0" name="product_size" id="id_product_size">Colour: {{ item.product.colour }}</p>

basket/templates/basket/product-image.html
<!-- Image placeholder for the basket -->
{% if item.product.image %}
<img class="img-fluid rounded" src="{{ item.product.image.url }}" alt="{{ item.product.name }}">
{% else %}
<img class="img-fluid rounded" src="{{ MEDIA_URL }}noimage.png" alt="{{ item.product.name }}">
{% endif %}

basket/templates/basket/product-info.html
<!-- Placeholder for the information of the product -->
<p class="my-0 fs-lg-5"><strong>{{ item.product.name }}</strong></p>
<p class="my-0 small text-muted">SKU: {{ item.product.sku|upper }}</p>
<p class="my-0 small text-muted">Colour: {{ item.product.colour }}</p>

basket/templates/basket/product-size.html
<!-- Placeholder for the product size -->
<p class="my-0" name="product_size" id="id_product_size">Size: {{ item.product.size }}</p>

basket/templates/basket/product_image.html
{% if item.product.image %}
<img class="img-fluid rounded" src="{{ item.product.image.url }}" alt="{{ item.product.name }}">
{% else %}
<img class="img-fluid rounded" src="{{ MEDIA_URL }}noimage.png" alt="{{ item.product.name }}">
{% endif %}